cc_library(
    name = "folly",
    srcs = glob(
        ["folly/**/*.cpp"],
        exclude = [
            "folly/**/test/**",
            "folly/**/tests/**",
            "folly/**/example/**",
            "folly/**/examples/**",
            "folly/**/tool/**",
            "folly/**/tools/**",

            "folly/futures/**",
            "folly/fibers/**",
            "folly/io/coro/**",
            "folly/io/async/**",
            "folly/io/async/ssl/**",
            "folly/python/**",
            "folly/executors/**",
            "folly/ssl/**",
            "folly/experimental/crypto/**",
            "folly/experimental/io/IoUringEventBaseLocal.cpp",
            "folly/experimental/io/IoUringBackend.cpp",
            "folly/experimental/io/SimpleAsyncIO.cpp",
            "folly/experimental/io/MuxIOThreadPoolExecutor.cpp",
            "folly/experimental/io/AsyncIoUringSocket.cpp",
            "folly/experimental/io/EpollBackend.cpp",
            "folly/experimental/io/IoUringEvent.cpp",
            "folly/experimental/TimerFD.cpp",
            "folly/experimental/TimerFDTimeoutManager.cpp",
            "folly/experimental/STTimerFDTimeoutManager.cpp",
            "folly/experimental/observer/**",
            "folly/portability/OpenSSL.cpp",
        ],
    ),
    hdrs = glob(["folly/**/*.h"]),
    includes = ["."],
    copts = [
      "-g",
      "-ggdb",
      "-O0",
      "-fno-omit-frame-pointer",
      "-gno-statement-frontiers",
      "-gno-variable-location-views",
      "-Wno-deprecated-declarations",
      "-Wno-deprecated",
      "-Wno-sign-compare",
      "-Wno-unknown-pragmas",
      "-Wno-unused-but-set-variable",
      "-Wno-unused-function",
      "-Wno-unused-value",
      "-Wno-unused-variable",
      "-Wno-unused-local-typedefs",
      "-Wno-maybe-uninitialized",
      "-mavx",
      "-mavx2",
      "-mpclmul",
      "-msse2",
    ],
    linkopts = [
        "-ldl",
        "-lpthread",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@boost//:algorithm",
        "@boost//:container",
        "@boost//:context",
        "@boost//:crc",
        "@boost//:filesystem",
        "@boost//:function_types",
        "@boost//:functional",
        "@boost//:interprocess",
        "@boost//:intrusive",
        "@boost//:multi_index",
        "@boost//:operators",
        "@boost//:preprocessor",
        "@boost//:program_options",
        "@boost//:regex",
        "@boost//:thread",
        "@boost//:conversion",
        "@boost//:variant",
        "@fmt",
        "@double-conversion",
        "@glog",
        "@zlib",
        # "@snappy",
        "@zstd",
        "@googletest//:gtest",
        "@openssl//:crypto",
        "@openssl//:ssl",
    ],
)
